language: node_js

node_js:
  - "6"

before_install:
  - npm install -g mocha

cache:
  directories:
    - "node_modules"

deploy:
  provider: gae
  keyfile: "client-secret.json.enc"
  project: "tipperu-1517012271502"
  on: master
