language: java
jdk:
    - oraclejdk8
node_js:
- '8'
before_install:
- npm install
- npm install -g mocha
- echo $TRAVIS_ENV_FILE > ./site/.env
cache:
  directories:
  - node_modules
before_deploy:
  - git stash --all
  - openssl aes-256-cbc -K $encrypted_71e887220f4c_key -iv $encrypted_71e887220f4c_iv
    -in client-secret.json.enc -out client-secret.json -d
  - echo $TRAVIS_ENV_FILE > ./site/.env
  - echo '!.env' >> .gitignore
script: npm test
deploy:
  skip_cleanup: true
  provider: gae
  keyfile: client-secret.json
  project: tipperu-1517012271502
  on: release
