#!/usr/bin/env node

/**
 * Module dependencies.
 */
'use strict';

var app = require('./app');
var debug = require('debug')('test:server');
var http = require('http');

require('dotenv').config({path:  __dirname + '/.env'});

/**
 * Get port from environment and store in Express.
 */

var port = normalizePort(process.env.PORT || '3000');
app.set('port', port);

/**
 * Create HTTP server.
 */

var server = http.createServer(app);

/**
 * Listen on provided port, on all network interfaces.
 */

server.on('listening', onListening);
server.on('error', onError);
server.listen(port);

var WebSocketServer = require('ws').Server,
	wss = new WebSocketServer({port: 40510});
wss.on('connection', function (ws) {
	ws.on('message', function (message) {
		console.log('received: %s', message);

		request('https://icanhazdadjoke.com/', { json: true }, (err, res, body) => {
			if (err) { return console.log(err); }
			ws.send(res.body.joke);
		});
	});
});

module.exports = {
  webserver: server,
  socketserver: wss
};

/**
 * Normalize a port into a number, string, or false.
 */

function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {
    // named pipe
    return val;
  }

  if (port >= 0) {
    // port number
    return port;
  }

  return false;
}

/**
 * Event listener for HTTP server "error" event.
 */

function onError(error) {
  if (error.syscall !== 'listen') {
    throw error;
  }

  var bind = typeof port === 'string'
    ? 'Pipe ' + port
    : 'Port ' + port;

  // handle specific listen errors with friendly messages
  switch (error.code) {
    case 'EACCES':
      console.error(bind + ' requires elevated privileges');
      process.exit(1);
      break;
    case 'EADDRINUSE':
      console.error(bind + ' is already in use');
      process.exit(1);
      break;
    default:
      throw error;
  }
}

/**
 * Event listener for HTTP server "listening" event.
 */

function onListening() {
  var addr = server.address();
  var bind = typeof addr === 'string'
    ? 'pipe ' + addr
    : 'port ' + addr.port;
  debug('Listening on ' + bind);
}
